version: '3'

services:
  postgres:
    container_name: fingreat_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - '/postgres/data'